sudo: required

services:
  - docker

before_install:
  -docker build -t arya04/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true arya04/react-test npm test

after_success:
  - docker build -t arya04/multi-client ./client
  - docker build -t arya04/multi-nginx ./nginx
  - docker build -t arya04/multi-server ./server
  - docker build -t arya04/multi-worker ./worker
  
  #Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #Take images and push to docker hub
  - docker push arya04/multi-client
  - docker push arya04/multi-nginx
  - docker push arya04/multi-server
  - docker push arya04/multi-worker